version: "3.9"
services:
  redis_container:
    image: redis:latest
    container_name: local-docker-redis-egg
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server /usr/local/conf/redis.conf

  egg-web:
    image: nginx
    container_name: local-docker-egg
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/servers:/etc/nginx/servers:ro
    command: [ nginx-debug, '-g', 'daemon off;' ]